### ISSUE TITLE
Example's root_id

### ISSUE THREAD

**Issue by esnible** [proxy-wasm/proxy-wasm-cpp-sdk#83]
The file README, [line 47](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blame/master/README.md#L47) registers the example with no root_id parameter.  I assume this picks up the default argument, `""`, but I couldn't get the example working without a root ID.  (I was using Istio EnvoyFilter to configure, perhaps mishandling an empty root_id is an Istio flaw, but it was confusing not to see a root ID in the example.

Consider running the spell checker on the docs (e.g. "from the version of **Enovy** you are going to deploy")

**Comment by bianpengyuan** [comment]
Empty root id should also be valid. I think it is something else that makes the example not working.. Most likely tool chain. I have a pending https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/71 to update both tool chain and the example to use bazel. Have not yet got time to finish that.

Meanwhile, you can reference this guide: https://github.com/istio-ecosystem/wasm-extensions/blob/master/doc/write-a-wasm-extension-with-cpp.md, which will be blog posted with 1.9.

**Comment by esnible** [comment]
I'm not trying to get into an argument with you.  I have retested it, and can confirm.

Using _myproject.cc_ with `static RegisterContextFactory register_ExampleContext(CONTEXT_FACTORY(ExampleContext), "my_root_id");` works; using it with `static RegisterContextFactory register_ExampleContext(CONTEXT_FACTORY(ExampleContext));` doesn't.

When using `"my_root_id"` my Istio EnvoyFilter contained

``` yaml
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: "http://example.com/"
              root_id: "my_root_id"
```

when using no string parameter to `register_ExampleContext()` my EnvoyFilter contained

``` yaml
          value:
            config:
              configuration:
                '@type': type.googleapis.com/google.protobuf.StringValue
                value: "http://example.com/"
              root_id: ""
```

The logs only appear when I use a non-empty root id.  I will try to troubleshoot this to see if it is a problem with Istio, Envoy, or this SDK.
